import puppeteer from "puppeteer";

export async function generatePDF(data: any): Promise<string> {
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });
  const page = await browser.newPage();

  // Filter out internal Kobo fields that start with "_" (except _submission_time maybe)
  const fieldsHtml = Object.entries(data)
    .filter(([key]) => !key.startsWith("_") || key === "_submission_time")
    .map(([key, value]) => {
      const label = key
        .replace(/_/g, " ")
        .replace(/\b\w/g, (char) => char.toUpperCase());
      const displayValue = typeof value === "object" ? JSON.stringify(value) : String(value);

      return `
        <div class="field">
          <div class="label">${label}</div>
          <div class="value">${displayValue || "-"}</div>
        </div>
      `;
    })
    .join("");

  const submissionDate = data._submission_time
    ? new Date(data._submission_time).toLocaleDateString()
    : new Date().toLocaleDateString();

  const useMock = process.env.MOCK_KOBO_DATA === "true" || process.env.MOCK_KOBO_DATA === undefined;
  const mockBanner = useMock 
    ? `<div style="background-color: #fef2f2; color: #b91c1c; padding: 15px; text-align: center; font-weight: bold; margin-bottom: 25px; border-radius: 8px; border: 2px dashed #b91c1c; text-transform: uppercase; letter-spacing: 1px;">
         TESTING MODE: This document contains simulated mock data and was not issued to a real participant.
       </div>` 
    : "";

  const html = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <style>
        body {
          font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
          color: #333;
          margin: 0;
          padding: 40px;
        }
        .header {
          text-align: center;
          padding-bottom: 20px;
          border-bottom: 3px solid #5e6f47;
          margin-bottom: 30px;
        }
        .header img {
          height: 60px;
          margin-bottom: 15px;
        }
        .header h1 {
          color: #5e6f47;
          margin: 0 0 10px 0;
          font-size: 28px;
        }
        .header p {
          color: #666;
          margin: 0;
          font-size: 14px;
        }
        .accent {
          color: #ecc750;
        }
        .content {
          display: flex;
          flex-direction: column;
          gap: 15px;
        }
        .field {
          background-color: #f9f9f9;
          padding: 15px;
          border-radius: 6px;
          border-left: 4px solid #ecc750;
        }
        .label {
          font-size: 12px;
          color: #666;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          margin-bottom: 5px;
        }
        .value {
          font-size: 16px;
          color: #111;
          font-weight: 500;
        }
        .footer {
          margin-top: 50px;
          text-align: center;
          font-size: 12px;
          color: #999;
          border-top: 1px solid #eee;
          padding-top: 20px;
        }
      </style>
    </head>
    <body>
      ${mockBanner}
      <div class="header">
        <img src="https://satorufoundation.org/logo.png" alt="Satoru Foundation" />
        <h1>Participant Submission</h1>
        <p>Document Generated &middot; <span class="accent">${submissionDate}</span></p>
      </div>
      
      <div class="content">
        ${fieldsHtml}
      </div>

      <div class="footer">
        Generated by Satoru Foundation Internal System &copy; ${new Date().getFullYear()}
      </div>
    </body>
    </html>
  `;

  await page.setContent(html);
  
  // Create PDF
  const pdfBuffer = await page.pdf({
    format: "A4",
    printBackground: true,
    margin: { top: "20px", bottom: "20px", left: "20px", right: "20px" },
  });

  await browser.close();

  return Buffer.from(pdfBuffer).toString("base64");
}
